# Generated by Django 4.2 on 2023-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WallApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
