# Generated by Django 4.2 on 2023-05-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WallApp', '0002_alter_productdb_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Message', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
