# Generated by Django 4.2 on 2023-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WallApp', '0003_feedbackdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdb',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
